
[[_bssswjicar_binary_sip_servlets_server_with_jboss_installing_configuring_and_running]]
= SIP Servlet-Enabled JBoss Application Server: Installing, Configuring and Running

The Restcomm SIP Servlets Server can run on either the JBoss Application Server or the Tomcat Servlet Container.
This section details how to install the SIP Servlets Server on top of the JBoss Application Server.
For installation instructions for the Tomcat Servlet Container, refer to <<_bssswticar_sip_servlets_server_with_tomcat_installing_configuring_and_running>> 

NOTE: It is recommended that the SIP Servlets Server is run on the JBoss platform.
Some functionality, including the ability to execute some SIP Extension examples, is not available in the Tomcat version.

.Differences Between a Standard JBoss Installation and the Restcomm SIP Servlets Version
Provided here is a list of differences between a standard JBoss Application Server installation one customized for SIP Servlets.
The differences include:

* The [path]_server/default/deploy_ directory contains both HTTP and SIP Servlet applications.
* The [path]_server/default/deploy/jbossweb.sar_ units have been modified to provide extended classes to the standard JBoss container classes, in order to allow SIP applications to be loaded and the SIP stack to be started.
* The [path]_server/default/deploy/jbossweb.sar_ [path]_context.xml_ files have been modified to allow the extended manager to manage SIP sessions and SIP application sessions in addition to HTTP sessions.
* The [path]_server/default/deploy/jbossweb.sar/_ [path]_server.xml_ file has been modified to provide extended classes to common JBoss Web containers.
  The classes allow SIP applications to be loaded, and the SIP stack to be started.
* The [path]_server/default/deploy/jbossweb.sar/_ [path]_jboss-beans.xml_ file has been modified to allow the JBoss container to process SIP messages.
* The [path]_server/default/deployers/_ [path]_metadata-deployer-jboss-beans.xml_ file has been modified to allow JBoss to parse sip.xml deployment descriptors and SIP metadata annotations.
* The [path]_server/default/deployers/jbossweb.deployer/META-INF/war-deployers-jboss-beans.xml_ file have been modified so that it is now possible for JBoss containers to correctly deploy SIP servlets and converged applications.
* A [path]_dars_ directory containing all of the Default Application Router (DAR) properties files for using the various SIP Servlets applications (which come bundled with the release) has been added to the [path]_server/default/conf_ directory.
* Additional JAR files have been added to enable SIP Servlet functionality; these are located in the [path]_server/default/deploy/jbossweb.sar/_, [path]_server/default/deployers/jbossweb.deployer/_ and [path]_common/lib_directories.

:leveloffset: 1
include::Common_Content/Java_Development_Kit-Installing_Configuring_and_Running.adoc[]
:leveloffset: 0

[[_bssswjicar_binary_sip_servlets_server_with_jboss_preinstall_requirements_and_prerequisites]]
== Pre-install Requirements and Prerequisites

.Hardware Requirements
Sufficient Disk Space::
  Once unzipped, version &VERSION;of the Restcomm SIP Servlets for JBoss binary release requires a minimum of &SSS_MSS4J_SIZE;free disk space.

Anything Java Itself Will Run On::
  Restcomm SIP Servlets for JBoss is 100% Java and will run on the same hardware that the JBoss Application Server runs on.

.Software Prerequisites
JDK 5 or Higher::
  A working installation of the Java Development Kit (<acronym>JDK</acronym>) version 5 or higher is currently required in order to run Restcomm SIP Servlets for JBoss binary distribution.
  For instructions on how to install the JDK, refer to <<_bssswjicar_binary_sip_servlets_server_with_jboss_installing>>

[[_bssswjicar_binary_sip_servlets_server_with_jboss_downloading]]
== Downloading

The latest version of Restcomm SIP Servlets for JBoss is available from &DOWNLOAD_LINK;link:.

Each version of the SIP Servlets Server is comprised of tree separate binary distribution files: one which is Restcomm SIP Servlets for JBoss, one which is Restcomm SIP Servlets for EAP and the other which is Restcomm SIP Servlets for Tomcat.
Download SIP Servlets Server for JBoss and continue with the following instructions.

[[_bssswjicar_binary_sip_servlets_server_with_jboss_installing]]
== Installing

Once the requirements and prerequisites have been met and you have downloaded the binary distribution zip file, you are ready to install the Restcomm SIP Servlets for JBoss binary distribution.
Follow the instructions below for the selected platform, whether Linux or Windows.

.Version Numbers
[NOTE]
====
For clarity, the command line instructions presented in this chapter use specific version numbers and directory names.
Ensure this information is substituted with the binary distribution's version numbers and file names.
====

.Procedure: Installing the Restcomm SIP Servlets for JBoss Binary Distribution on Linux

It is assumed that the downloaded archive is saved in the home directory, and that a terminal window is open displaying the home directory
. Create a subdirectory to extract the Restcomm  SIP Servlets for JBoss files into.
  For ease of identification, it is recommended that the version number of the binary is included in this directory name.
+
----
~]$ mkdir "-jboss-<version>"
----

. Move the downloaded zip file into the directory.
+
----
~]$ mv "" "-jboss-<version>"
----

. Move into the directory.
+
----
~]$ cd "-jboss-<version>"
----

. Extract the files into the current directory by executing one of the following commands.
+
Java: 
----
-jboss-<version>]$ jar -xvf ""
* ----
Linux: 
----
-jboss-<version>]$ unzip ""
* ----
+
NOTE: You can also use `unzip`'-d <unzip_to_location> to extract the zip file's contents to a location other than the current directory.

. To free disk space, you may want to delete the zip file once you've extracted its contents:
+
----
-jboss-<version>]$ rm ""
----


.Procedure: Installing the Restcomm  for JBoss Binary Distribution on 

For this procedure, it is assumed that the downloaded archive is saved in the [path]_My Downloads_ folder.
. Create a directory in [path]_My Downloads_ to extract the zip file's contents into.
  For ease of identification, it is recommended that the version number of the binary is included in the folder name.
  For example, [path]_-jboss-<version>_.
. Extract the contents of the archive, specifying the destination folder as the one created in the previous step.
. Alternatively, execute the `jar -xvf` command to extract the binary distribution files from the zip archive.
+
. Move the downloaded zip file from [path]_My Downloads_ to the folder created in the previous step.
. Open the Windows Command Prompt and navigate to the folder that contains the archive using the `cd` command
. Execute the `jar -xvf` command to extract the archive contents into the current folder.
+
----
C:\Users\<user>\My Downloads\-jboss-<version>>jar -xvf ""
----


. It is recommended that the folder holding the Restcomm for JBoss files (in this example, the folder named [path]_-jboss-<version>_) is moved to a user-defined location for storing executable programs.
  For example, the [path]_Program Files_ folder.
. Consider deleting the archive, if free disk space is an issue.
+
----
C:\Users\<user>\My Downloads\-jboss-<version>>delete ""
----


[[_bssswjicar_binary_sip_servlets_server_with_jboss_setting_the_jboss_home_environment_variable]]
== Setting the JBOSS_HOME Environment Variable

Configuring Restcomm for JBoss consists of setting the [var]`JBOSS_HOME` environment variable and optionally customizing the Restcomm  for JBoss server by adding SIP Connectors, configuring the application router, and logging.

After setting [var]`JBOSS_HOME` according to the instructions in the following section, refer to <<_bsssc_binary_sip_servlets_server_configuring>> to learn how to configure Restcomm  for JBoss.

Alternatively, after having set [var]`JBOSS_HOME`, the Restcomm  for JBoss server can be run.
Return to this section to configure it later. 

:leveloffset: 2
include::Common_Content/Setting_the_JBOSS_HOME_Environment_Variable.adoc[]
:leveloffset: 0

[[_bssswjicar_binary_sip_servlets_server_with_jboss_configuring]]
== Configuring

To configure Restcomm for JBoss, refer to <<_bsssc_binary_sip_servlets_server_configuring>>.

[[_bssswjicar_binary_sip_servlets_server_with_jboss_running]]
== Running

To start the server, execute one of the startup scripts in the [path]_bin_ directory (on Linux or Windows), or by double-clicking the [path]_run.bat_ executable batch file in that same directory (on Windows only).  It is recommended that the JBoss Application Server is started using the terminal or Command Prompt because the messages displayed during startup can be used to debug, and subsequently correct, any problems.
In the Linux terminal or Command Prompt, a successfully started server will return the following information :

[source]
----
22:39:07,598 INFO  [SipApplicationDispatcherImpl]  Sip Servlets <version> - revision <rev number> started.
----

Detailed instructions are given below, arranged by platform.

.Procedure: Running Restcomm  for JBoss on Linux
. Change the working directory to Restcomm for JBoss's installation directory (the one in which the zip file's contents was extracted to)
+
----
downloads]$ cd "-jboss-<version>"
----

. (Optional) Ensure that the [path]_bin/run.sh_ start script is executable.
+
----
-jboss-<version>]$ chmod +x bin/run.sh
----

. Execute the [path]_run.sh_ Bourne shell script.
+
----
-jboss-<version>]$ ./bin/run.sh
----


[NOTE]
====
Instead of executing the Bourne shell script to start the server, the [path]_run.jar_ executable Java archive can be executed from the [path]_bin_ directory:

----
-jboss-<version>]$ java -jar bin/run.jar
----
====

.Procedure: Running Restcomm  for JBoss on 

There are several ways to start Restcomm for JBoss on Windows.
All of the following methods accomplish the same task.
. Using Windows Explorer, navigate to the [path]_bin_ subdirectory in the installation directory.
. The preferred way to start Restcomm for JBoss from the Command Prompt.
  The command line interface displays details of the startup process, including any problems encountered during the startup process.
+
Open the Command Prompt via the [label]#Start# menu and navigate to the correct folder:
+
----
C:\Users\<user>My Downloads> cd "-jboss-<version>"
----

Start the JBoss Application Server by executing one of the following files: 

* [path]_run.bat_ batch file:
+
----
C:\Users\<user>My Downloads\-jboss-<version>>bin\run.bat
----

* [path]_run.jar_ executable Java archive:
+
----
C:\Users\<user>My Downloads\-jboss-<version>>java -jar bin\run.jar
----

[[_bssswjicar_binary_sip_servlets_server_with_jboss_using]]
== Using

Once the server is running, access the SIP Servlets Management Console by opening http://localhost:8080/sip-servlets-management/.

== Testing

After installation, there should be one pre-configured sample application deployed in the `default` server onfiguration.
You can use it to verify that the server is installed and running correctly.
The application name is "`org.mobicents.servlet.sip.example.SimpleApplication`".
From the Sip Servlets Management Console you can make sure it is subscribed to receive `INVITE` and `REGISTER` SIP requests.
It is a simple [path]_Click2Call_ application allowing SIP registration and calling phones from the Web user interface.

The scenario for this example consists of the following steps:

. Alice and Bob each register a SIP Softphone
. Alice clicks on the "Call" link to place a call to Bob
. Alice's phone rings
. When Alice picks up her phone, Bob's phone rings
. When Bob answers his phone, the call is connected
. When one of them hangs up, the other one is also disconnected 

.Procedure: Testing the Click2Call sample application
. Open up a browser to http://localhost:8080/click2call/.
  If you have no registered SIP clients you will be asked to register at least two.
. Configure your SIP clients to use the sip servlets server as a register and proxy.
  (IP address : 127.0.0.1, port: 5080) By default it will accept any password
. After the registration you will see a table where each cell will initiate a call between the corresponding clients.
. Close the calls.
. Navigate to http://localhost:8080/click2call/simplecall.html, which is a simplified version that doesn't require registered clients. 
. Enter the URIs of the two SIP phones you just started and click "Submit"
. The phones should be ringing again.
  You can pick them up and you will know that the SIP and the HTTP containers are working properly.

[[_bssswjicar_binary_sip_servlets_server_with_jboss_stopping]]
== Stopping

Detailed instructions for stopping the JBoss Application Server are given below, arranged by platform.
If the server is correctly stopped, the following three lines are displayed as the last output in the Linux terminal or Command Prompt:

[source]
----
[Server] Shutdown complete
Shutdown complete
Halting VM
----

.Procedure: Stopping Restcomm  for JBoss on Linux
. Change the working directory to the binary distribution's install directory.
+
----
~]$ cd "-jboss-<version>"
----

. (Optional) Ensure that the bin/shutdown.sh start script is executable:
+
----
-jboss-<version>]$ chmod +x bin/shutdown.sh
----

. Run the [path]_shutdown.sh_ executable Bourne shell script with the [option]`-S` option (the short option for [option]`--shutdown`) as a command line argument:
+
----
-jboss-<version>]$ ./bin/shutdown.sh -S
----


[NOTE]
====
The [path]_shutdown.jar_ executable Java archive with the [option]`-S` option can also be used to shut down the server:

----
-jboss-<version>]$ java -jar bin/shutdown.jar -S
----
====

.Procedure: Stopping &CMD_PLATFORM_NAME; for JBoss on Windows
. Stopping the JBoss Application Server on Windows consists in executing either the [path]_shutdown.bat_ or the [path]_shutdown.jar_ executable file in the [path]_bin_ subdirectory of the Restcomm  for JBoss binary distribution.
  Ensure the [option]`-S` option (the short option for [option]`--shutdown`) is included in the command line argument.
+
----
C:\Users\<user>\My Downloads\-jboss-<version>>bin\shutdown.bat -S
----
+
a. The [path]_shutdown.jar_ executable Java archive with the [option]`-S` option can also be used to shut down the server:
+
----
C:\Users\<user>\My Downloads\-jboss-<version>>java -jar bin\shutdown.jar -S
----



[[_bssswjicar_binary_sip_servlets_server_with_jboss_uninstalling]]
== Uninstalling

To uninstall Restcomm for JBoss, delete the directory containing the binary distribution.
