import java.net.URL;
import java.util.Collection;
import java.util.HashMap;
import java.util.Iterator;

import javax.servlet.sip.ServletTimer;
import javax.servlet.sip.SipApplicationSession;
import javax.servlet.sip.SipApplicationSessionAttributeListener;
import javax.servlet.sip.SipApplicationSessionBindingEvent;
import javax.servlet.sip.SipApplicationSessionBindingListener;
import javax.servlet.sip.SipSession;
import javax.servlet.sip.URI;

import org.apache.catalina.deploy.LoginConfig;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : sip-servlets
//  @ File Name : SipServletApplicationImpl.java
//  @ Date : 2007-09-27
//  @ Author : 
//
//




public class SipServletApplicationImpl implements SipApplicationSession{
	
	
	//----- GENERATED FROM STAR UML
	private String _applicationName;
	private String _smallIcon;
	private String _largeIcon;
	private String _displayName;
	private String _description;
	private boolean _distributable;
	private HashMap _contextParams;
	private SipListenersHolder _listeners;
	private String _mainServlet;
	private HashMap _servlets;
	private HashMap _servletMapping;
	private int _proxyTimeout;
	private int _sessionTimeout;
	private HashMap _resourceEnvRefs;
	private HashMap _resourcesRef;
	private HashMap _securityConstraints;
	private LoginConfig _loginConfig;
	private HashMap _securityRoles;
	private HashMap _envEntries;
	private HashMap _ejbRefs;
	private HashMap _ejbLocalRefs;
	private HashMap<String,Object> _sipApplicationSessionAttributeMap;
	
	//------ END GENERATED
	private HashMap<String,SipSession> id2SipSession;
	
	public void encodeURI(URI uri) {
		// TODO Auto-generated method stub
		
	}
	public URL encodeURL(URL url) {
		// TODO Auto-generated method stub
		return null;
	}
	public Object getAttribute(String name) {
		// TODO Auto-generated method stub
		return null;
	}
	public Iterator<String> getAttributeNames() {
		// TODO Auto-generated method stub
		return null;
	}
	public long getCreationTime() {
		// TODO Auto-generated method stub
		return 0;
	}
	public long getExpirationTime() {
		// TODO Auto-generated method stub
		return 0;
	}
	public String getId() {
		// TODO Auto-generated method stub
		return null;
	}
	public long getLastAccessedTime() {
		// TODO Auto-generated method stub
		return 0;
	}
	public Iterator<?> getSessions() {
		// TODO Auto-generated method stub
		return null;
	}
	public Iterator<?> getSessions(String protocol) {
		// TODO Auto-generated method stub
		return null;
	}
	public SipSession getSipSession(String id) {
		// TODO Auto-generated method stub
		return null;
	}
	public Collection<ServletTimer> getTimers() {
		// TODO Auto-generated method stub
		return null;
	}
	public void invalidate() {
		// TODO Auto-generated method stub
		
	}
	public boolean isValid() {
		// TODO Auto-generated method stub
		return false;
	}
	public void removeAttribute(String name) {
		
		
		if(!isValid())
			throw new IllegalStateException("Can not bind object to session that has been invalidated!!");
		
		if(name==null)
			//throw new NullPointerException("Name of attribute to bind cant be null!!!");
			return;
	
		
		SipApplicationSessionBindingEvent event=new SipApplicationSessionBindingEvent(this,name);
		
		for(SipApplicationSessionBindingListener l:this._listeners.getSipApplicationSessionBindingListeners())
		{
			l.valueUnbound(event);
			
		}
		
		for(SipApplicationSessionAttributeListener l: this._listeners.getSipApplicationSessionAttributeListeners())
		{
			l.attributeRemoved(event);
		}
		
		this._sipApplicationSessionAttributeMap.remove(name);
	}
	public void setAttribute(String key, Object attribute) {
		
		
		if(!isValid())
			throw new IllegalStateException("Can not bind object to session that has been invalidated!!");
		
		if(key==null)
			throw new NullPointerException("Name of attribute to bind cant be null!!!");
		if(attribute==null)
			throw new NullPointerException("Attribute that is to be bound cant be null!!!");
		
		
		SipApplicationSessionBindingEvent event=new SipApplicationSessionBindingEvent(this,key);
		if(_sipApplicationSessionAttributeMap.containsKey(key))
		{
			//This is initial, we need to send value bound event
			
			for(SipApplicationSessionBindingListener l:this._listeners.getSipApplicationSessionBindingListeners())
			{
				l.valueBound(event);
				
			}
			
			for(SipApplicationSessionAttributeListener l: this._listeners.getSipApplicationSessionAttributeListeners())
			{
				l.attributeAdded(event);
			}
			
		}else
		{
			
			for(SipApplicationSessionAttributeListener l: this._listeners.getSipApplicationSessionAttributeListeners())
			{
				l.attributeReplaced(event);
			}
			
		}
		
		
		this._sipApplicationSessionAttributeMap.put(key, attribute);
		
	}
	public int setExpires(int deltaMinutes) {
		// TODO Auto-generated method stub
		return 0;
	}
	public SipListenersHolder getListeners() {
		return _listeners;
	}
	public void setListeners(SipListenersHolder listeners) {
		this._listeners = listeners;
	}
	
	
	
}
