package org.mobicents.servlet.sip.startup.loading;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : sip-servlets
//  @ File Name : SecurityRole.java
//  @ Date : 08/10/2007
//  @ Author : 
//
//




public class SecurityRole {
	public String description;
	public String roleName;
}
