
[[_mipbx_media_ipbx]]
= Media IPBX

The Media IPBX provides an extensible and customizable SIP PBX solution, based on the Seam Telco Framework (STF).  While the PBX is currently provided as a capability demonstration, the ultimate goal is to transition Media IPBX into a fully-fledged SIP PBX solution.

Media IPBX terminates all calls to Restcomm Media Server conference endpoints, which provides flexibility in manipulating established calls including server-side conferencing and ring-back tones.
The PBX can also be implemented as a Session Border Controller.

NOTE: Media IPBX is compatible with Restcomm SIP Servlets with JBoss AS 4.2.3.
Versions prior to this release do not support Media IPBX.

Media IPBX provides the following major features: 

* User authentication.
* SIP phone registration.
* System configuration.
* Individual user views.
* Call monitoring and management.
* Multiple SIP phone instances per user.
* Status-based SIP phone assignment for incoming calls.
* Public Switched Telephone Network (PSTN) support, including administrative functions.
* Support for SIP REGISTER requests to automatically add phones by matching the username, or username and hostname (in 'strict mode' only).
* Optionally specify local or online sources for announcements and ringback tones.
* Session Border Controller capability.
* Full conferencing support, including:
+
* Privacy functions, including mute and closed-calls.
* Call status announcement.
* Ringback tones when waiting for other participants to join the conference.
* Joining incoming calls to a conference.
* Parking calls and isolating a single speaker using dual-tone multi-frequency (DTMF) tones.
  This feature is currently experimental.
    

Many of the features in Media IPBX are presented to the user as hints on the GUI portal pages.
It is recommended that you install Media IPBX and experiment with the demonstration to gain an understanding of how the solution works.

For information about installing and running Media IPBX, including binary and source code locations, visit the http://www.mobicents.org/mss-ipbx.html[Media IPBX homepage].
