
[[_mssstun_mss_stun]]
= STUN
= Enterprise Monitoring and Management
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .

The Session Traversal Utilities for NAT (STUN) prococol is used in Network Address Translation (NAT) traversal for real-time voice, video, messaging, and related interactive IP application communications.
This light-weight, client-server protocol allows applications passing through a NAT to obtain the public IP address for the UDP connections the application uses to connect to remote hosts.

STUN support is provided at the SIP connector level, using the https://stun4j.dev.java.net/[STUN for Java] project.
The STUN for Java project provides a Java implementation of the STUN Protocol (RFC3489), which allows each SIP connector to select whether it should use STUN to discover a public IP address, and then use this address in the SIP messages sent through the connector.

To make a SIP connector STUN-enabled, three attributes must be appended to the <connector> tag in the server.xml file.
The properties are: 

* useStun="true"
+
Enables STUN support for this connector.
Ensure that the `ipAddress` attribute is not set to `127.0.0.1`.

* stunServerAddress="<public_STUN_Server>"
+
STUN server address used to discover the public IP address of this SIP Connector.
See the table below for a suggested list of public STUN servers.

* stunServerPort="3478"
+
STUN server port of the STUN server used in the `stunServerAddress` attribute.
Both TCP and UDP protocols communicate with STUN servers using this port only.
    

NOTE: A list of available SIP connector attributes and their descriptions is located in the <<_bsssc_binary_sip_servlets_server_adding_sip_connectors>> section of this user guide.

A number of public STUN servers are available, and can be specified in the `stunServerAddress`.
Depending on the router firmware used, the MAPPED_ADDRESS in STUN reply packets may be changed to the router's WAN port as they pass through particular router brands.
To alleviate this problem, certain public STUN servers provide XOR_MAPPED_ADDRESS support.
A selection of the public STUN servers is provided below.

[cols="1,1,1"]
|===










|===
